name: Merge dev into qa
description: "Composite action merge dev into qa"

inputs:
  GITHUB_TOKEN:
    description: Override GitHub Token
    required: true

runs:
  using: 'composite'
  steps:
    - name: Merge Dev into qa
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        pr_url="$(gh pr create -B qa --head dev --title "[Automated] Merged dev into target qa" --body "")"
        gh pr merge --admin --squash "$pr_url"