name: Validate PR
description: "Composite action check pr"

inputs:
  GITHUB_TOKEN:
    description: Override GitHub Token
    required: true

runs:
  using: 'composite'
  steps:
    - uses: thehanimo/pr-title-checker@7fbfe05602bdd86f926d3fb3bccb6f3aed43bc70
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        pass_on_octokit_error: false
        github_configuration_repo: test-repo
        github_configuration_path: .github/actions/pr-simple-validation/pr-title-checker-config.json